### ISSUE TITLE
Possibilité d'ajouter la "Distribution" d'un contenu ? 

### ISSUE THREAD

**Issue by Mpoposki** [discoverability/discoverability#3]
Afin de mener une analyse pertinente sur le contenu que propose Netflix, serait-il possible d'ajouter la "distribution" d'un contenu ? Page 16 de la documentation.
(url)
[Documentation & Data Dictionary - IMDb and Box Office Mojo.pdf](https://github.com/discoverability/discoverability/files/5603895/Documentation.Data.Dictionary.-.IMDb.and.Box.Office.Mojo.pdf)

**Comment by Grigou-X** [comment]
Ok, je vois ça ce week-end et je ferais un compte rendu de la faisabilité ou non. @Mpoposki

**Comment by nherbaut** [comment]
@Grigou-X any progress?

**Comment by Grigou-X** [comment]
Après discussion avec @Mpoposki et quelques recherches. Il n'est pas possible à première vue de récupérer les companies de chaque imdb_id. 

Cependant, il faudrait contacter directement imdb pour nous donner accès à ce genre d'information.

**Comment by Mpoposki** [comment]
I had a call with @nherbaut during the week and he found a way to retrieve this data without going through IMDB Pro. With the tt code (ie: tt10048342) of a content found on Netflix and a JS code (below) we can get all the companies involved in the production of the content identifed by his tt code. 

JS code to use on the[ IMDB Company Credits]( https://www.imdb.com/title/tt5157456/companycredits?ref_=tt_dt_co) page :
`for(let prod of document.querySelectorAll("#production +ul>li>a")){
console.log(prod.innerHTML);
}`

During the next few weeks I will be working on the development in PHP of a solution to retrieve the company(ies) associated with the TT code of a content. This code will use and produce a JSON (This exchange will be done with IMDB Importer). In addition to giving the distribution of a content we will also be able to find in the database a new table with the companies and their IMDB IDs (ie: [co0433793](https://www.imdb.com/search/title/?companies=co0433793)).

**Comment by nherbaut** [comment]
@Mpoposki did you make any progress on this?

**Comment by nherbaut** [comment]
deployed in production
