### ISSUE TITLE
Collect total number of appearance of each thumbnail and respective their positions

### ISSUE THREAD

**Issue by gemb0y** [discoverability/discoverability#4]
It would be very interesting to have the ability to collect the total number of appearance of each thumbnail and their positions in the user interface.
For example for movie 1 :
- id of movie
- how many times its thumbnail appeared in total
- position 1 (row, column), how many times it appeared at this position
- position 2 (row, column), how many times it appeared at this position
- position 3 ...
- ...
That's it! 
Hope you'll be able to achieve that as it will give very useful information about the recommandations on Netflix.

**Comment by nherbaut** [comment]
Added a new endpoint in testing https://experimental-api.vod-prime.space/api/netflix

it provides a counter to know how many times the thumbnails appeared in the system (https://experimental-api.vod-prime.space/api/netflix/thumbnails).
It also provides links for each thumbnail to show where it was located and to which user it was suggested (e.g. https://experimental-api.vod-prime.space/api/netflix/thumbnail/70011213)
let me know if it works for you

**Comment by nherbaut** [comment]
@Grigou-X @GregBidz  deployed to testing, please test if it works for you before production

**Comment by nherbaut** [comment]
@GregBidz @Grigou-X up

**Comment by GregBidz** [comment]
I get the following error message on 'api/netflix' endpoint: "The requested URL was not found on the server"

**Comment by nherbaut** [comment]
should be ok now @GregBidz @Grigou-X

**Comment by GregBidz** [comment]
ok, works for me

**Comment by nherbaut** [comment]
deployed to production
