### ISSUE TITLE
Connaitre le pays dans lequel une session est visualisé

### ISSUE THREAD

**Issue by janine34** [discoverability/discoverability#6]
Est-il possible de connaitre le pays dans lequel une session est visualisé?

**Comment by nherbaut** [comment]
We deployed in the testing environment new json data that includes the anonymised IP address and the country for a user.

Steps to test: 
1. go to https://experimental-api.vod-prime.space
2. click on the users resources
3. select a user, for this user browse to the "links" sub-resource and click on the "all-sessions" href
4. You should have all the sessions for a user, 
5. For each session, you should have the anonymized ip address (ending with a .0)
6. For each session, you should have a link with the rel ="country"
7. when clicking on the "country" href, you should see the country for the session with 3rd party ipinfo.io service

example link : https://experimental-api.vod-prime.space/api/user/1dc3c156-8e8b-4df7-aa98-d5362b49633c/sessions

**Comment by nherbaut** [comment]
related to https://github.com/discoverability/user-data-collector/issues/30

**Comment by nherbaut** [comment]
deployed in production
https://hapi.vod-prime.space/api/user/1dc3c156-8e8b-4df7-aa98-d5362b49633c/sessions
