### ISSUE TITLE
Analyser / Récupérer le programme de diffusion de Netflix Direct

### ISSUE THREAD

**Issue by Mpoposki** [discoverability/discoverability#7]
Netlfix déploie en France une nouvelle option de visionnage : Direct. Est-il possible de récupérer le programme de cette diffusion continue ? 

"Que vous soyez en panne d’inspiration, ou que vous découvriez Netflix pour la première fois, vous pourrez vous laisser porter sans avoir à choisir un titre en particulier et vous laisser surprendre par la diversité du catalogue Netflix"

https://about.netflix.com/fr/news/direct-new-feature-tested-in-france

**Comment by nherbaut** [comment]
This makes sense. @Mpoposki do you have any idea where to get this information from? We could implement scraping, but it would be easier with a reliable API

**Comment by nherbaut** [comment]
Scrapping implemented for the direct schedule. @Mpoposki could you please validate that the schedule from the API is correct?
https://hapi.vod-prime.space/direct

**Comment by nherbaut** [comment]
@oualidGuennif could you please let us know when this robot could be launched in production https://github.com/stream-for-good/scrapping-robots?
So far, it's running out of my own raspi

**Comment by nherbaut** [comment]
deployed in production
